### ISSUE TITLE
ImportError: No module named 'seg_utils'

### ISSUE THREAD

**Issue by andrewssobral** [MarvinTeichmann/KittiSeg#103] opened 2017-08-02 12:57 UTC
I just tried to run: ```python demo.py --input_image data/demo/demo.png```
and this error occurs:
```
Traceback (most recent call last):
  File "demo.py", line 51, in <module>
    from seg_utils import seg_utils as seg
ImportError: No module named 'seg_utils'
```

**Comment by MarvinTeichmann** [comment] 2017-08-02 13:01
Duplicate of issue #17

**Comment by andrewssobral** [comment] 2017-08-02 13:19
Thank you @MarvinTeichmann !
Sorry for the duplicated issue. 
The demo code runs, but unfortunately it crashes due to GPU memory limitation I think:
```
2017-08-02 15:17:23.558831: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:940] Found device 0 with properties:
name: Quadro K2000M
major: 3 minor: 0 memoryClockRate (GHz) 0.745
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-08-02 15:17:23.558995: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:961] DMA: 0
2017-08-02 15:17:23.561364: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   Y
2017-08-02 15:17:23.561952: I c:\tf_jenkins\home\workspace\release-win\m\windows-gpu\py\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K2000M, pci bus id: 0000:01:00.0)
2017-08-02 15:17:24,017 INFO /u/marvin/no_backup/RUNS/KittiSeg/loss_bench/xentropy_kitti_fcn_2016_10_15_01.18/model.ckpt-15999
INFO:tensorflow:Restoring parameters from RUNS\KittiSeg_pretrained\model.ckpt-15999
2017-08-02 15:17:24,017 INFO Restoring parameters from RUNS\KittiSeg_pretrained\model.ckpt-15999
```

**Closed** 2017-08-02 13:53 UTC
